Repository Sylius/SyliusDemo, pull requests merged in 2020-01, with the labels that each got.

#116 Add migration from Sylius/Sylius#11012
  src/Migrations/Version20200110132702.php
Labels: Maintenance

#117 Fix template after menu taxon introduction
  composer.lock
  templates/bundles/SyliusShopBundle/layout.html.twig
Labels: Bug

#118 Hotfix - problem with date displaying
  config/packages/twig.yaml
Labels: Bug

#115 Use BitBagCmsPlugin in Shop
  config/packages/_sylius.yaml
  templates/Shop/Homepage/Block/_carousel.html.twig
  templates/bundles/SyliusShopBundle/Homepage/Block/_aboutUs.html.twig
  templates/bundles/SyliusShopBundle/Homepage/Block/_banner.html.twig
  templates/bundles/SyliusShopBundle/Homepage/Block/_latestProductsCarousel.html.twig
Labels: Feature

#119 [Maintenance] Remove unused lib
  .travis.yml
  composer.lock
  config/bundles.php
  config/packages/sonata_core.yaml
  config/packages/twig_extensions.yaml
  symfony.lock
Labels: Maintenance
