Repository Sylius/SyliusDemo, pull requests merged in 2022-02, with the labels that each got.

#222 [Maintenance] Change build badge from Travis to GitHub Action in README file
  README.md
Labels: Maintenance

#221 [Maintenance] Add Sylius/Calendar to bundles
  config/bundles.php
Labels: Maintenance

#220 [Maintenance] Support Sylius 1.11.0-BETA.1
  .env
  .env.test
  .github/workflows/build.yml
  .travis.yml
  .travis/behat.yml
  README.md
  behat.yml.dist
  composer.json
  composer.lock
  config/api_platform/.gitkeep
  config/bundles.php
  config/packages/framework.yaml
  config/packages/security.yaml
  config/routes/dev/twig.yaml
  public/index.php
  src/EventListener/ChannelListener.php
  src/Kernel.php
  symfony.lock
  tests/Behat/Context/Ui/Shop/RegistrationContext.php
Labels: Maintenance

#226 [Security] Force authentication for users
  config/packages/security.yaml
Labels: Bug

#228 [Maintenance] Turn on API reference on stable demo
  composer.lock
  config/packages/_sylius.yaml
Labels: Enhancement, Maintenance

#230 [Maintenance] Update gulp-sass version
  .github/workflows/build.yml
  package.json
Labels: Maintenance
