Repository Sylius/SyliusDemo, pull requests merged in 2023-03, with the labels that each got.

#277 [Maintenance] Add security polyfill
  .env
  .env.test
  .env.test_cached
  config/bundles.php
Labels: Maintenance, dependencies

#278 [Maintenance] Add security polyfill
  .env
  .env.test
  .env.test_cached
  config/bundles.php
Labels: Bug, Maintenance, dependencies

#279 Add PriceHistoryPlugin to stable demo
  composer.json
  composer.lock
  config/bundles.php
  config/packages/_sylius.yaml
  config/packages/doctrine.yaml
  config/routes/sylius_admin.yaml
  src/Entity/Channel.php
  src/Entity/ChannelPricing.php
Labels: dependencies

#280 Fix integration between the refund and the PayPal plugin
  templates/bundles/SyliusAdminBundle/Order/Show/_payment.html.twig
Labels: Bug
