Repository Sylius/SyliusDemo, pull requests merged in 2024-11, with the labels that each got.

#293 [Maintenance] Bump demo to 1.14
  .env
  .github/workflows/build.yml
  composer.json
  config/bundles.php
  config/packages/_sylius.yaml
  config/packages/knp_snappy.yaml
  config/packages/sylius_invoicing.yaml
  config/packages/sylius_refund.yaml
  config/routes.yaml
  config/routes/sylius_admin.yaml
  config/routes/sylius_invoicing.yaml
  config/routes/sylius_refund.yaml
  config/routes/sylius_shop.yaml
  config/services_test.yaml
  symfony.lock
  tests/Behat/Resources/config/services.xml
  tests/Behat/Resources/config/suites.yml
Labels: Maintenance

#294 Fix demo dependencies
  composer.json
Labels: Maintenance, dependencies

#296 [Maintenance] Change demo urls 1.14
  templates/Blocks/_infoBox.html.twig
Labels: Maintenance

#295 [Maintenance] Change demo urls 2.0
  templates/info_box.html.twig
Labels: Maintenance

#307 Update API url in select box in 1.14
  templates/Blocks/_infoBox.html.twig
Labels: Enhancement

#308 Update API url in select box in 2.0
  templates/info_box.html.twig
Labels: Enhancement

#299 [Maintenance] Add sylius/paypal-plugin
  composer.json
  config/bundles.php
  config/packages/_sylius.yaml
  config/packages/http_discovery.yaml
  config/routes.yaml
  config/routes/sylius_admin.yaml
  config/routes/sylius_shop.yaml
  symfony.lock
  templates/bundles/SyliusShopBundle/Checkout/SelectPayment/_choice.html.twig
  templates/bundles/SyliusShopBundle/Common/Order/_addresses.html.twig
Labels: Maintenance

#314 [Maintenance] Add sylius/paypal-plugin
  composer.json
  config/bundles.php
  config/packages/_sylius.yaml
  config/packages/fos_rest.yaml
  config/routes.yaml
  config/routes/sylius_admin.yaml
  config/routes/sylius_shop.yaml
  symfony.lock
Labels: Maintenance
